export const REVIEWED_COLOR_PAGES: Record<string, { task: string; reference?: string; checked?: string; measuredLrv?: number }> = {
  "behr/chic-gray-ppu26-10": { task: "Compare gray alternatives using the same trim sample. Behr describes Chic Gray as a cool silvery gray; a database undertone label may differ from that manufacturer description.", reference: "https://www.behr.com/colors/color-detail/ppu26-10", checked: "2026-09-20", measuredLrv: 60 },
  "dunn-edwards/play-on-gray-de6228": { task: "Use DE6228 when requesting a sample so the store can identify this color precisely. Compare the nearest digital alternatives beside your flooring before switching brands.", reference: "https://www.dunnedwards.com/colors/browser/de6228/", checked: "2026-09-20" },
  "dunn-edwards/legendary-gray-de6369": { task: "Use DE6369 to distinguish Legendary Gray from similarly named shades. Compare a sample in your intended finish on both a lit and a shaded part of the wall.", reference: "https://www.dunnedwards.com/colors/browser/de6369/", checked: "2026-09-20" },
  "sherwin-williams/sea-salt-6204": { task: "Sherwin-Williams lists Sea Salt in its green family. Compare its physical sample with your trim; our digital gray-family classification is not a prediction of its appearance.", reference: "https://www.sherwin-williams.com/en-us/color/color-family/green-paint-colors/sw6204-sea-salt", checked: "2026-09-20" },
  "benjamin-moore/october-mist-1495": { task: "Identify October Mist by code 1495. When comparing alternatives, keep the sample size and finish the same so the color difference is easier to judge." },
  "ppg/prairie-dust-1102-4": { task: "Use the Prairie Dust code 1102-4 when asking a retailer about availability. If substituting a different brand, order its own sample rather than relying on a shared color name." },
  "dutch-boy/minnesota-pines-328-7db": { task: "Keep code 328-7DB with your shortlist. Compare the available alternatives with the original sample in both daylight and evening light before choosing a replacement." },
  "dutch-boy/acadian-green-226-6db": { task: "Use code 226-6DB to identify Acadian Green. A similar name in another catalog does not establish a match; compare the ranked digital candidates and then physical samples." },
};
