// Per-family undertone descriptions used in the FAQPage JSON-LD and the
// visible FAQ section on family hub pages. Plain text (no JSX) so they
// flow into structured-data answer fields.
//
// Each entry targets the 134-167 word range the GEO audit identified as
// the optimal length for AI-engine citation. Structure: paragraph 1
// covers the undertone families and named designer staples; paragraph 2
// is practical sampling/lighting/room-fit guidance specific to that
// family. The second paragraph is the differentiation lever — it's
// where each family's answer carries unique applied advice rather than
// the same template with substitutions.

export const FAMILY_UNDERTONE_ANSWERS: Record<string, string> = {
  white:
    "White paint colors come in three undertone families. Warm whites lean cream, yellow, or peach (Benjamin Moore White Dove, Sherwin-Williams Pure White). Cool whites lean blue or gray (Benjamin Moore Chantilly Lace, Sherwin-Williams Snowbound). True neutral whites are rare. Match the white's undertone to your fixed elements — warm floors and brass hardware call for warm whites; cool tile and chrome call for cool whites. When sampling whites, look at them on the actual wall not the chip — whites amplify lighting cast more than any other family. Test in three places: a north-facing wall, a south-facing wall, and a wall next to any major fixed element (tile, countertop, woodwork) so you can see how the white reads against your existing palette. Trim and ceiling whites can differ from wall whites; matching all three is more important than picking a single best white.",
  "off-white":
    "Off-white paint colors are defined by their underlying warm cast. Cream, ivory, ecru, oat, and bone tones all sit here. Most lean toward yellow-warm undertones rather than cool gray, which makes them forgiving in north-facing rooms where pure whites can read sterile. Designer staples include Benjamin Moore Swiss Coffee and Sherwin-Williams Alabaster. Off-whites carry just enough warmth to soften rooms without reading as full cream — they sit at the most forgiving balance between brightness and warmth. Use them in transition spaces (hallways, foyers, open-plan flow) where pure cool whites would feel cold and warm creams would feel dated. When sampling, place a 4x4 swatch alongside your existing trim and base mouldings — the off-white should feel intentional against the trim, not muddy. Filter by undertone above to find off-whites that lean warmer or pull toward a cooler greige.",
  gray:
    "Grays come in three distinct undertone families. Blue-leaning grays read crisp and cool; green-leaning grays feel earthy and architectural; purple-leaning grays warm slightly under 2700K incandescent light. Warm grays like Sherwin-Williams Agreeable Gray and Benjamin Moore Revere Pewter lean tan. Cool grays like Benjamin Moore Pewter and Sherwin-Williams Repose Gray stay closer to neutral. When choosing a gray, place a 4x4 sample on the actual wall and observe it under three light conditions: morning daylight, mid-afternoon direct sun, and evening 2700K bulb light. Most gray failures come from picking a chip under store fluorescents that reads very differently at home. If the gray is the dominant whole-room color, prioritize warm-leaning grays in north-facing rooms and cool-leaning grays in south-facing rooms with abundant natural light. Cool-light environments mute gray's warmth and can pull it slightly green; warm-light environments push grays toward beige.",
  neutral:
    "Neutral paint colors sit on the border between gray and beige — greige is the technical name. They're temperature-flexible: warm neutrals lean tan or pink, cool neutrals lean gray-blue, and true neutrals show neither bias. Benjamin Moore Edgecomb Gray and Revere Pewter are the most-searched greiges. Greige is the dominant neutral category sold today because it bridges warm beige eras and cool gray eras without committing to either. When evaluating a neutral, look at its lightness and its bias separately — a 50-LRV greige reads heavier than the 65-LRV version of the same color name. Sample in your largest room first; subtle bias amplifies at scale. White trim with a neutral-greige wall is the most forgiving combination across paint brands and works against the widest range of existing flooring tones. Test the neutral against your warmest and coolest fixed elements simultaneously to confirm it doesn't fight either.",
  beige:
    "Beige paint colors carry warm undertones — yellow, gold, peach, or red. The cleanest beiges, like Sherwin-Williams Accessible Beige and Benjamin Moore Manchester Tan, avoid the pink or orange cast that dates older beiges. Modern beige favors a slight green or gray push for greige territory. Beige fell out of favor in the 2010s because warm yellow-gold versions dated quickly; today's beiges read cleaner because they lean closer to the greige border. When sampling, place the swatch next to any cool-toned fixed element you already have (white tile, chrome, marble) — old-style beiges fight cool finishes, modern greiges blend with them. Beige works best with natural materials (wood, linen, leather) rather than high-contrast modern hardware. Always check it under 4000K LED lighting alongside the warm-bulb evening preview. Modern beiges work especially well in open-plan spaces where they unify the visual flow between rooms.",
  tan:
    "Tan paint colors fall between beige and brown — warmer than beige, lighter than chocolate. Common undertones are yellow (sandy, oat) and red (rose-tan, ochre). Tans pair naturally with warm woods, leather, and brass; they feel less formal than gray and warmer than off-white, which makes them popular for hallways and family rooms. Pure neutral tans are rare — most lean either warmer toward camel or cooler toward greige. Modern tans like Manchester Tan or Bone White lean cleaner than 1990s harvest tans. Sample on a wall adjacent to your floor and trim; tans need to harmonize with both warm wood floors and white trim. If your floors are cool-stained oak, choose a cooler tan; if they're warm walnut, lean into the warmth. Sample under both daylight and lamp light to see the true bias.",
  brown:
    "Brown paint colors range from cool taupe and mushroom to warm chocolate, cocoa, and espresso. Undertones are usually red, yellow, or violet. Light browns like Benjamin Moore Camel Back read as warm neutrals; medium browns like Sherwin-Williams Java anchor furniture-grade spaces; deep browns like Benjamin Moore Iron Mountain work as accents and exteriors. Browns absorb a lot of light, so check LRV before committing — a 10-LRV chocolate reads dramatically different from a 25-LRV warm taupe. Deep browns work as architectural accents (built-ins, libraries, dining rooms) but lose their richness in north-facing rooms with weak natural light. When pairing browns with other earth tones, vary the LRV by at least 15 points to maintain contrast — same-tone, same-LRV combinations read muddy. Brown also needs to read against your largest furniture piece — match the wood-stain undertone or contrast deliberately rather than accidentally.",
  black:
    "Black paint colors aren't monolithic. True blacks like Benjamin Moore Black Beauty sit near LRV 5. Softer blacks like Sherwin-Williams Tricorn Black and Benjamin Moore Wrought Iron hover around LRV 6-8 with subtle undertones — brown, blue, or green. The undertone matters most on walls where you'll see large fields of color; trim and accent uses are more forgiving. Pair true blacks with crisp whites; pair soft blacks with warm whites and natural wood. Black walls have become mainstream architectural choices in the last decade. Pure blacks work in spaces with abundant natural light and quality artificial fixtures — they reflect what you give them. Soft blacks work better in low-light rooms because they don't pull the room into pure dark. Match black trim or accents to your hardware finishes for visual coherence. Black in satin or eggshell sheen shows fingerprints far less than flat finish on high-touch surfaces.",
  red:
    "Red paint colors come in two main undertone families. Warm reds with yellow or orange bias produce terracotta, brick, and rust. Cool reds with blue or violet bias produce raspberry, wine, and oxblood. Sherwin-Williams Cherry Tomato is a saturated warm red; Benjamin Moore Caliente is the iconic Color of the Year red — balanced and true. Reds intensify under 2700K bulbs and can read pinker under 4000K daylight. When testing reds, evaluate them under both lighting conditions and place samples on a wall opposite a window so you see the morning vs. evening shift. For dining rooms and libraries — the classic red rooms — deeper reds like Caliente lean burgundy; brighter reds like Cherry Tomato read younger. Reserve true reds for accent walls; warmer earth-reds work for full rooms. Pair reds with crisp warm whites for trim.",
  orange:
    "Orange paint colors range from soft peach and apricot through terracotta and burnt sienna to vibrant tangerine. Undertones are typically yellow (sandy, ochre) or red (rust, copper). Warm earth-oranges like Sherwin-Williams Cavern Clay and Benjamin Moore Spiced Pumpkin pair with warm wood floors, brass, and natural materials. Bright oranges work best as accent walls or in active rooms — kitchens, playrooms, home offices. Orange is making a comeback in warm-earth form (terra cotta, burnt sienna) after decades of being avoided; the modern orange palette reads grounded rather than energetic. Sample at multiple times of day; oranges intensify dramatically under late-afternoon warm light. In kitchens and family rooms, warm-orange accents pair well with brass and terracotta tile. Vibrant oranges work as single accent walls in active spaces — playrooms, home offices, mudrooms. Saturated oranges read younger and more playful than deep earth-oranges, so match the saturation to the room's purpose.",
  yellow:
    "Yellow paint colors come in three temperature zones. Warm yellows like butter, gold, and honey lean orange or red. Cool yellows like lemon and citrus lean green. Balanced yellows like creamy and custard sit in between. Benjamin Moore Hawthorne Yellow is a designer staple. Yellow paints amplify lighting differences more than most families — a butter yellow under 2700K bulbs can shift to gold, while the same wall under 4000K daylight reads truer to the chip. Test in the actual room before committing. Pale yellows work well in north-facing rooms that need warmth; saturated yellows are accent territory (single walls, mudrooms, laundry rooms). Pair yellow with navy or deep teal for contrast — same-temperature pairings (yellow plus warm beige) tend to read muddy. Avoid yellow ceilings unless the room is purpose-built for warmth — they cast a sallow tint across the entire space.",
  green:
    "Green paint colors carry more undertone variation than any other family. Blue-greens (teal, emerald, jade) read cool. Yellow-greens (olive, sage, moss) read warm. Pure greens (forest, kelly) sit in between. Sherwin-Williams Evergreen Fog and Benjamin Moore Saybrook Sage are popular sages; deeper choices like Hunter Green or Farrow & Ball Calke Green go architectural. Green is the most forgiving accent color in residential paint because the human eye is most sensitive to the green range — small shifts read as different colors rather than off-versions of the same color. Sage greens work as whole-room neutrals in north-facing spaces. Bluer greens read crisp and architectural. Earthier greens ground rooms with natural materials. Sample against your existing wood floors — green reacts strongly to floor tone. Green also looks meaningfully different in summer-foliage daylight versus winter-bare-tree daylight; sample across seasons if possible.",
  blue:
    "Blue paint colors split into three undertone families. Green-blues (teal, peacock, aqua) lean warmer; pure blues (cornflower, sky, navy) sit in the middle; red-blues (periwinkle, indigo, deep navy) lean cooler. Benjamin Moore Hale Navy is the most-searched modern navy; lighter staples like Sherwin-Williams Sea Salt and Benjamin Moore Healing Aloe lean toward soft spa territory. When testing blues, sample on the wall opposite your largest light source — blues shift more under indirect light than direct. Cool blues work well in rooms with cool fixed elements (chrome, white tile, gray-stained wood); warm blues pair better with brass, warm wood, and cream-toned finishes. For bedrooms, mid-LRV blues feel calming without going dim. Saturated navies work in dining rooms, libraries, and powder rooms — small high-impact spaces. Blue ceilings (sky-blue, robin's egg) also work as architectural accents that visually brighten low ceilings.",
  purple:
    "Purple paint colors are the most lighting-sensitive family. Cool purples (lavender, lilac, violet) lean blue. Warm purples (plum, eggplant, mauve) lean red. Under 2700K warm bulbs all purples push toward mauve or pink; under 4000K daylight they keep their violet integrity. Light purples work as bedroom accent walls; deep eggplants like Farrow & Ball Pelt make dramatic dining rooms. Purple benefits most from extensive sampling — place a 4x4 swatch on each of the four walls in your room and observe under daylight, lamp light, and overhead lighting before committing. Pale purples work in bedrooms with cool natural light. Pair purples with cool whites for trim if you want them to read crisp, or with warm whites if you want them to soften and read more pink-violet. Test purples specifically at sunset golden hour — that's when they shift most dramatically toward mauve.",
  pink:
    "Pink paint colors range from soft blush and powder pink through coral and salmon to vibrant magenta and fuchsia. Undertones are usually peach (warm, leaning orange) or true pink (cool, leaning blue-violet). Designer staples include Benjamin Moore Pink Bliss and Sherwin-Williams Faint Coral. Warm pinks glow under 2700K bulbs and lean coral; cool pinks stay more saturated and slightly cooler under daylight. Pinks are the most popular paint family for nurseries and bedrooms because they age well — unlike saturated colors, soft pinks transition through life stages (nursery to child's room to guest room) without feeling locked-in. Test pinks under both 2700K warm bulbs and 4000K daylight. Pair pinks with deep green or navy accents for contrast — pure white trim against pink reads sweet, while off-white trim adds maturity. Pinks also work in unexpected exterior applications — clay pink stucco or coral trim on white houses.",
};
