import type { NextConfig } from "next";
import { readFileSync } from "node:fs";
import { join } from "node:path";

// Old-slug → canonical-slug map written by scripts/dedupe-colors.ts when
// duplicate color rows (dual numbering systems, import dupes) are consolidated.
// These must stay deployed as long as the old URLs have inbound links/index
// entries — the rows they pointed at are deleted from the DB.
const colorRedirects: Record<string, string> = JSON.parse(
  readFileSync(join(process.cwd(), "src/data/color-redirects.json"), "utf8"),
);

// Fonts are self-hosted via next/font (Manrope + Inter, see app/layout.tsx),
// so we don't need to allow fonts.googleapis.com/gstatic.com in CSP. They
// were vestigial entries from an earlier external-CDN font setup.
const contentSecurityPolicy = [
  "default-src 'self'",
  "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://www.google-analytics.com https://pagead2.googlesyndication.com https://googleads.g.doubleclick.net https://tpc.googlesyndication.com https://adservice.google.com https://*.adtrafficquality.google https://va.vercel-scripts.com https://s.pinimg.com https://*.pinterest.com",
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data: blob: https:",
  "font-src 'self' data:",
  "connect-src 'self' https://*.supabase.co https://*.google-analytics.com https://*.analytics.google.com https://*.googletagmanager.com https://pagead2.googlesyndication.com https://*.adtrafficquality.google https://vitals.vercel-insights.com https://ct.pinterest.com",
  "frame-src https://googleads.g.doubleclick.net https://*.googlesyndication.com https://*.adtrafficquality.google https://www.google.com https://*.pinterest.com",
  "object-src 'none'",
  "base-uri 'self'",
  "form-action 'self'",
  "frame-ancestors 'self'",
].join("; ");

const securityHeaders = [
  {
    key: "Content-Security-Policy",
    value: contentSecurityPolicy,
  },
  // X-Frame-Options removed — the CSP `frame-ancestors 'self'` directive is the
  // modern equivalent and supersedes it in all current browsers.
  {
    key: "X-Content-Type-Options",
    value: "nosniff",
  },
  {
    key: "Referrer-Policy",
    value: "strict-origin-when-cross-origin",
  },
  {
    key: "Cross-Origin-Opener-Policy",
    value: "same-origin-allow-popups",
  },
  {
    key: "Strict-Transport-Security",
    value: "max-age=31536000; includeSubDomains; preload",
  },
  {
    key: "Permissions-Policy",
    value: "camera=(), microphone=(), geolocation=()",
  },
];

// The /embed/* routes are meant to be iframed on third-party sites (the free
// cross-brand match widget — a link/citation engine). Loosen ONLY the
// frame-ancestors directive to `*` for those routes; every other security header
// stays identical. The global rule below excludes /embed/ so this is the only
// CSP that applies there (duplicate CSP headers would intersect to the strictest).
const embedContentSecurityPolicy = contentSecurityPolicy.replace(
  "frame-ancestors 'self'",
  "frame-ancestors *",
);
const embedSecurityHeaders = securityHeaders.map((h) =>
  h.key === "Content-Security-Policy" ? { ...h, value: embedContentSecurityPolicy } : h,
);

const nextConfig: NextConfig = {
  // Frozen at build time (this file evaluates once per build) so sitemap
  // lastmod values reflect the actual deploy date instead of resetting to
  // "today" on every ISR cold-start — which Googlebot reads as false freshness.
  env: {
    SITE_BUILD_DATE: new Date().toISOString().split("T")[0],
  },
  // Suppress the X-Powered-By: Next.js fingerprinting header.
  poweredByHeader: false,
  htmlLimitedBots:
    /Mediapartners-Google|AdsBot-Google|Googlebot|Google-InspectionTool|Google-PageRenderer|Slurp|DuckDuckBot|baiduspider|yandex|sogou|bitlybot|tumblr|vkShare|quora link preview|redditbot|ia_archiver|Bingbot|bingbot|BingPreview|msnbot|applebot|facebookexternalhit|facebookcatalog|Twitterbot|LinkedInBot|Slackbot|Discordbot|SkypeUriPreview|Bytespider|SeznamBot|Pinterestbot|PetalBot|WhatsApp|AhrefsBot|AhrefsSiteAudit|SemrushBot|DotBot|MJ12bot|Screaming Frog|Sitebulb|DeepCrawl|OnCrawl|Bloodhound/i,
  images: {
    // OG/swatch images generated by /api/og and /api/pin are deterministic
    // by hex + name params, but without a TTL Vercel re-processes them every
    // 60 seconds. 24h is appropriate — the underlying inputs don't change.
    minimumCacheTTL: 86400,
    remotePatterns: [
      { hostname: "lh3.googleusercontent.com" },
      { hostname: "avatars.githubusercontent.com" },
    ],
  },
  async redirects() {
    return [
      // Non-www → www redirect lives in vercel.json (the Vercel edge layer
      // processes those before Next.js rewrites, so a redirect here is dead
      // code). Keeping the path-level redirects below since vercel.json
      // doesn't carry them.
      {
        source: "/colors/family/taupe",
        destination: "/colors/family/beige",
        permanent: true,
      },
      {
        source: "/blog",
        has: [{ type: "query", key: "tag", value: "Design" }],
        destination: "/blog?tag=design",
        permanent: true,
      },
      {
        source: "/blog",
        has: [{ type: "query", key: "tag", value: "Guide" }],
        destination: "/blog?tag=guide",
        permanent: true,
      },
      {
        source: "/blog",
        has: [{ type: "query", key: "tag", value: "Trends" }],
        destination: "/blog?tag=trends",
        permanent: true,
      },
      {
        source: "/blog",
        has: [{ type: "query", key: "tag", value: "Tips" }],
        destination: "/blog?tag=tips",
        permanent: true,
      },
      // MPC (Matthews Paint) removed 2026-06: sign/metal coatings, not
      // homeowner wall paint. ~2 Google clicks in 3 months across 1,419 pages.
      {
        source: "/colors/mpc/:path*",
        destination: "/brands",
        permanent: true,
      },
      {
        source: "/brands/mpc",
        destination: "/brands",
        permanent: true,
      },
      {
        source: "/match/mpc/:path*",
        destination: "/brands",
        permanent: true,
      },
      {
        source: "/match/:brand/to/mpc",
        destination: "/brands",
        permanent: true,
      },
      // Deduped color rows: old slug → canonical slug (161 entries).
      ...Object.entries(colorRedirects).map(([from, to]) => ({
        source: `/colors/${from}`,
        destination: `/colors/${to}`,
        permanent: true,
      })),
    ];
  },
  async rewrites() {
    return [
      {
        source: "/sitemap.xml",
        destination: "/api/sitemap",
      },
      {
        source: "/sitemap/:id.xml",
        destination: "/api/sitemap/:id",
      },
    ];
  },
  async headers() {
    return [
      {
        // Embed routes excluded here — they get the permissive frame-ancestors
        // CSP below so they can be iframed on third-party sites.
        source: "/((?!api/|_next/static/|_next/image/|favicon.ico|embed/).*)",
        headers: securityHeaders,
      },
      {
        source: "/embed/:path*",
        headers: embedSecurityHeaders,
      },
    ];
  },
};

export default nextConfig;
