/**
 * Generates src/lib/retailer-overrides.ts from the JSON results
 * of check-retailer-links.ts runs.
 *
 * Usage: npx tsx scripts/generate-retailer-overrides.ts
 */
import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

interface OverrideEntry {
  slug: string;
  colorNumber: string;
  ourFamily: string;
  correctFamily: string;
}

interface CheckResult {
  overrides: OverrideEntry[];
  notFound: string[];
  checked: number;
  passed: number;
}

const brands = ["valspar", "ppg", "sherwin-williams", "dunn-edwards", "kilz", "colorhouse", "ral"] as const;

function loadResults(brand: string): CheckResult | null {
  const file = path.resolve(__dirname, `retailer-links-${brand}.json`);
  if (!fs.existsSync(file)) {
    console.log(`  Skipping ${brand} (no results file)`);
    return null;
  }
  return JSON.parse(fs.readFileSync(file, "utf-8"));
}

function parseNotFoundNumber(entry: string): string | null {
  const match = entry.match(/\(([^)]+)\)/);
  return match ? match[1] : null;
}

function toTsKey(brand: string): string {
  return brand.replace(/-/g, "_").toUpperCase();
}

function main() {
  const lines: string[] = [];
  lines.push("// Auto-generated by scripts/generate-retailer-overrides.ts");
  lines.push("// Maps color number → correct website family for colors where our guess was wrong");
  lines.push("");

  for (const brand of brands) {
    console.log(`Processing ${brand}...`);
    const data = loadResults(brand);
    if (!data) continue;

    const key = toTsKey(brand);

    // Override map: colorNumber → correctFamily
    lines.push(`export const ${key}_OVERRIDES: Record<string, string> = {`);
    for (const o of data.overrides) {
      const num = o.colorNumber.replace(/"/g, '\\"');
      const fam = o.correctFamily.replace(/"/g, '\\"');
      lines.push(`  "${num}": "${fam}",`);
    }
    lines.push("};");
    lines.push("");

    // Not-found set: color numbers that don't exist on the website
    const notFoundNumbers = data.notFound
      .map(parseNotFoundNumber)
      .filter((n): n is string => n !== null);

    lines.push(`export const ${key}_NOT_FOUND = new Set([`);
    for (const num of notFoundNumbers) {
      lines.push(`  "${num.replace(/"/g, '\\"')}",`);
    }
    lines.push("]);");
    lines.push("");

    console.log(`  ${data.overrides.length} overrides, ${notFoundNumbers.length} not found`);
  }

  const outFile = path.resolve(__dirname, "../src/lib/retailer-overrides.ts");
  fs.writeFileSync(outFile, lines.join("\n") + "\n");
  console.log(`\nWritten to ${outFile}`);
}

main();
