// Swatch lane — single-color reference pins from the priority catalog
// (board: Paint Colors). Image is the programmatic /api/pin swatch; data comes
// from swatch-colors.json (generated by build-swatch-colors.ts).
import * as path from "path";
import { fileURLToPath } from "url";
import * as fs from "fs";
import type { PinSpec } from "../batch-may26.ts";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SITE = "https://www.paintcolorhq.com";
const UTM = "?utm_source=Pinterest&utm_medium=organic&utm_campaign=swatch-drip";

interface SwatchColor {
  brandSlug: string;
  slug: string;
  brandName: string;
  name: string;
  hex: string;
  code: string | null;
  lrv: number | null;
  family: string | null;
}

const DATA: SwatchColor[] = JSON.parse(
  fs.readFileSync(path.resolve(__dirname, "../swatch-colors.json"), "utf8"),
);

export function swatchPins(): PinSpec[] {
  return DATA.map((c) => {
    const params = new URLSearchParams({ hex: c.hex, name: c.name, brand: c.brandName });
    if (c.code) params.set("code", c.code);
    if (c.lrv != null) params.set("lrv", String(Math.round(c.lrv)));
    if (c.family) params.set("family", c.family);
    const lrvNote = c.lrv != null ? `, LRV ${Math.round(c.lrv)}` : "";
    return {
      id: 0,
      key: `swatch-${c.brandSlug}-${c.slug}`,
      type: "swatch",
      board: "Paint Colors",
      theme: c.family ?? "color",
      format: "swatch",
      name: `${c.brandName} ${c.name}`,
      image: "",
      imageUrl: `${SITE}/api/pin?${params.toString()}`,
      prompt: "",
      title: `${c.name}${c.code ? ` ${c.code}` : ""} — ${c.brandName} Paint Color`,
      description: `${c.brandName} ${c.name}${c.code ? ` (${c.code})` : ""} — ${c.family ?? "paint"} paint color${lrvNote}. See it in a real room and find the best place to buy it at PaintColorHQ.`,
      link: `${SITE}/colors/${c.brandSlug}/${c.slug}${UTM}`,
    } as PinSpec;
  });
}
